# E:/cross_camera_tracking/pyproject.toml
[project]
name = "cross_camera_tracking"
version = "0.1.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["backend"]