"""add image_path to realtime_match_alert_table

Revision ID: 3d29d557baba
Revises: 
Create Date: 2025-08-10 09:23:01.945351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d29d557baba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_alerts_id', table_name='alerts') # 注释掉：alerts 表不存在
    # op.drop_table('alerts') # 注释掉：alerts 表不存在
    op.add_column('global_search_results', sa.Column('individual_id', sa.Integer(), nullable=False, comment='关联的 Individual ID'))
    op.add_column('global_search_results', sa.Column('matched_person_id', sa.Integer(), nullable=False, comment='匹配到的人物 ID'))
    op.add_column('global_search_results', sa.Column('user_id', sa.Integer(), nullable=False, comment='发起搜索的用户 ID'))
    op.add_column('global_search_results', sa.Column('is_initial_search', sa.Boolean(), nullable=False, comment='是否为首次关注人物时触发的搜索'))
    op.alter_column('global_search_results', 'matched_person_uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=36),
               comment='匹配到的人物 UUID',
               existing_nullable=False)
    op.alter_column('global_search_results', 'matched_image_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               type_=sa.String(length=255),
               comment='匹配到的图片路径',
               existing_nullable=False)
    op.alter_column('global_search_results', 'confidence',
               existing_type=mysql.FLOAT(),
               comment='比对置信度',
               existing_nullable=False)
    op.alter_column('global_search_results', 'search_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               comment='搜索时间')
    op.drop_index('ix_global_search_results_matched_person_uuid', table_name='global_search_results')
    op.drop_index('ix_global_search_results_query_person_uuid', table_name='global_search_results')
    op.create_foreign_key(None, 'global_search_results', 'individuals', ['individual_id'], ['id'])
    op.create_foreign_key(None, 'global_search_results', 'persons', ['matched_person_id'], ['id'])
    op.create_foreign_key(None, 'global_search_results', 'users', ['user_id'], ['id'])
    op.drop_column('global_search_results', 'query_person_uuid')
    op.drop_column('global_search_results', 'full_frame_image_path')
    op.add_column('realtime_match_alerts', sa.Column('image_path', sa.String(length=255), nullable=True, comment='预警图片路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realtime_match_alerts', 'image_path')
    op.add_column('global_search_results', sa.Column('full_frame_image_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=True))
    op.add_column('global_search_results', sa.Column('query_person_uuid', mysql.VARCHAR(collation='utf8mb4_general_ci', length=36), nullable=False))
    op.drop_constraint(None, 'global_search_results', type_='foreignkey')
    op.drop_constraint(None, 'global_search_results', type_='foreignkey')
    op.drop_constraint(None, 'global_search_results', type_='foreignkey')
    op.create_index('ix_global_search_results_query_person_uuid', 'global_search_results', ['query_person_uuid'], unique=False)
    op.create_index('ix_global_search_results_matched_person_uuid', 'global_search_results', ['matched_person_uuid'], unique=False)
    op.alter_column('global_search_results', 'search_time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='搜索时间')
    op.alter_column('global_search_results', 'confidence',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='比对置信度',
               existing_nullable=False)
    op.alter_column('global_search_results', 'matched_image_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=500),
               comment=None,
               existing_comment='匹配到的图片路径',
               existing_nullable=False)
    op.alter_column('global_search_results', 'matched_person_uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=36),
               comment=None,
               existing_comment='匹配到的人物 UUID',
               existing_nullable=False)
    op.drop_column('global_search_results', 'is_initial_search')
    op.drop_column('global_search_results', 'user_id')
    op.drop_column('global_search_results', 'matched_person_id')
    op.drop_column('global_search_results', 'individual_id')
    # op.create_table('alerts', # 注释掉：alerts 表不存在
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联到 Person 表的ID'),
    # sa.Column('matched_image_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=False, comment='预警时匹配到的人物裁剪图路径'),
    # sa.Column('full_frame_image_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=True, comment='预警时匹配到的完整帧图片路径'),
    # sa.Column('confidence', mysql.FLOAT(), nullable=False, comment='预警匹配的置信度'),
    # sa.Column('alert_time', mysql.TIMESTAMP(), nullable=True, comment='预警发生的时间'),
    # sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='alerts_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_general_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False) # 注释掉：alerts 表不存在
    # ### end Alembic commands ###
