"""Add cropped_image_path and full_frame_image_path to realtime_match_alerts

Revision ID: 410c5f8bd8e9
Revises: 3d29d557baba
Create Date: 2025-08-12 13:39:43.782981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '410c5f8bd8e9'
down_revision: Union[str, None] = '3d29d557baba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realtime_match_alerts', sa.Column('cropped_image_path', sa.String(length=255), nullable=False, comment='预警人物裁剪图片路径'))
    op.add_column('realtime_match_alerts', sa.Column('full_frame_image_path', sa.String(length=255), nullable=False, comment='预警原始图片（全帧）路径'))
    op.drop_column('realtime_match_alerts', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realtime_match_alerts', sa.Column('image_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='预警图片路径'))
    op.drop_column('realtime_match_alerts', 'full_frame_image_path')
    op.drop_column('realtime_match_alerts', 'cropped_image_path')
    # ### end Alembic commands ###
