"""Add realtime_comparison_enabled to FollowedPerson

Revision ID: d0dcd8aa69df
Revises: ced855b24283
Create Date: 2025-08-05 21:12:30.316571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dcd8aa69df'
down_revision: Union[str, None] = 'ced855b24283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followed_persons', sa.Column('realtime_comparison_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followed_persons', 'realtime_comparison_enabled')
    # ### end Alembic commands ###
